[package]
name = "dfint-installer"
version = "0.1.3"
edition = "2021"
build = "build.rs"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[dependencies]
anyhow = "1.0.75"
checksum = "0.2.1"
crc32fast = "1.3.2"
eframe = "0.23.0"
egui-modal = "0.2.5"
egui-notify = "0.10.0"
egui_extras = { version = "0.23.0", features = ["all_loaders"] }
egui_file = "0.11.0"
env_logger = "0.11.1"
exe = "0.5.6"
serde = "1.0.190"
serde_derive = "1.0.190"
serde_json = "1.0.108"
static_init = "1.0.3"
sys-locale = "0.3.1"
sysinfo = "0.29.10"
ureq = { version = "2.9.1", features = ["json"] }
