[package]
name = "dfint-installer"
version = "0.1.4"
edition = "2021"
build = "build.rs"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[dependencies]
anyhow = "1.0.79"
checksum = "0.2.1"
crc32fast = "1.4.0"
eframe = "0.23.0"
egui-modal = "0.2.5"
egui-notify = "0.10.0"
egui_extras = { version = "0.23.0", features = ["all_loaders"] }
egui_file = "0.11.0"
env_logger = "0.11.2"
exe = "0.5.6"
include_dir = "0.7.3"
serde = "1.0.190"
serde_derive = "1.0.190"
serde_json = "1.0.114"
static_init = "1.0.3"
sys-locale = "0.3.1"
sysinfo = "0.29.11"
ureq = { version = "2.9.6", features = ["json"] }
